# start from the rocker/r-ver:3.5.0 image. This is used as the base container
FROM rocker/r-ver:3.5.0

# install the linux libraries needed for plumber. Check for the newest packages and install 2 which arent in the std update
RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev

# install plumber
RUN R -e "install.packages(c('plumber','data.table'))"

# copy everything from the current directory into the container
COPY / /

# open port 80 to traffic
EXPOSE 80

# when the container starts, start the main.R script
ENTRYPOINT ["Rscript", "main.R"]